// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.acme.doktorics.model;

import com.acme.doktorics.model.Client;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Client_Roo_Configurable {
    
    declare @type: Client: @Configurable;
    
}
